version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:00"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "fix(deps)"
      prefix-development: "chore(deps-dev)"
      include: "scope"
    labels:
      - "dependencies"
      - "security"
    groups:
      security-updates:
        applies-to: security-updates
        patterns:
          - "*"
        
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    commit-message:
      prefix: "ci"
    labels:
      - "github-actions"
      - "ci"